Pass argument separately to categorize script and fail in case of error in pipeline

diff --git a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
--- a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
+++ b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
@@ -7,6 +7,9 @@ parameters:
 
 steps:
 - script: |
+    set -e  # Exit immediately if a command exits with a non-zero status
+    set -u  # Treat unset variables as an error
+    set -o pipefail  # Return the exit status of the last command in the pipeline that failed
     git fetch origin
     echo "Fetching changes from origin rc = $?"
     echo "SOURCE_BRANCH: ${{ parameters.SOURCE_BRANCH }}"
@@ -36,7 +39,7 @@ steps:
 
       if [[ -n "$IMPACTED_TESTS" ]]; then
         IMPACTED_TEST_SCRIPTS=$(echo "$IMPACTED_TESTS" | jq -r '(.tests // []) | join(" ")')
-        TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/categorize_test_scripts_by_topology.py --files "$IMPACTED_TEST_SCRIPTS")
+        TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/categorize_test_scripts_by_topology.py --files $IMPACTED_TEST_SCRIPTS)
         echo "Test scripts:"
         echo "$TEST_SCRIPTS"
         sudo apt-get -o DPkg::Lock::Timeout=600 -y install jq
