Integrate updated impact area algorithm to pipeline
Signed-off-by: opcoder0 <110003254+opcoder0@users.noreply.github.com>

diff --git a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
--- a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
+++ b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
@@ -1,82 +1,43 @@
+parameters:
+  - name: TARGET_BRANCH
+    type: string
+    default: 'origin/master'
+  - name: SOURCE_BRANCH
+    type: string
+
 steps:
 - script: |
-    set -x
+    git fetch origin
+    echo "Fetching changes from origin rc = $?"
+    CHANGED_FILES=$(git diff --name-only ${{ parameters.TARGET_BRANCH }})
+    echo "Changed files:"
+    echo "$CHANGED_FILES"
 
-    git fetch --all
-    DIFF_FOLDERS=$(git diff $(git merge-base origin/master HEAD)..HEAD  --name-only | xargs -n1 dirname | sort -u | tr '\n' ' ')
+    IMPACTED_TESTS=$(python ./.azure-pipelines/impacted_area_testing/detect_impacted_area.py --modified_files "$CHANGED_FILES" --feature_branch ${{ parameters.SOURCE_BRANCH }} --target_branch ${{ parameters.TARGET_BRANCH }} --directory tests --no-log)
+    echo "Impacted tests:"
+    echo "$IMPACTED_TESTS"
 
-    if [[ $? -ne 0 ]]; then
-      echo "##vso[task.complete result=Failed;]Get diff folders fails."
-      exit 1
-    else
-      echo -n "##vso[task.setvariable variable=DIFF_FOLDERS]$DIFF_FOLDERS"
-    fi
-
-  continueOnError: false
-  displayName: "Get diff folders"
-
-- script: |
-    set -x
-
-    pip install PyYAML
-    pip install natsort
-
-    sudo apt-get -o DPkg::Lock::Timeout=600 -y install jq
-
-    FINAL_FEATURES=""
-    IFS=' ' read -ra FEATURES_LIST <<< "$(DIFF_FOLDERS)"
-
-    # Define the list of folders include common features
-    COMMON_DIRS=("tests/common" "tests/scripts")
-
-    for FEATURE in "${FEATURES_LIST[@]}"
-    do
-      for COMMON_DIR in "${COMMON_DIRS[@]}"; do
-        if [[ "$FEATURE" == *$COMMON_DIR* ]]; then
-          FINAL_FEATURES=""
-          break 2
-        fi
-      done
-
-      # If changes only limited to specific feature, the scope of PR testing is impacted area.
-      if [[ "$FEATURE" =~ ^tests\/.* ]]; then
-        # Cut the feature path
-        if [[ $FEATURE == */*/* ]]; then
-            FEATURE=$(echo "$FEATURE" | cut -d'/' -f1-2)
-        fi
-
-        FEATURE=${FEATURE#tests/}
-
-        if [[ -z "$FINAL_FEATURES" ]]; then
-          FINAL_FEATURES="$FEATURE"
-        elif [[ ! "$FINAL_FEATURES" == *$FEATURE* ]]; then
-          FINAL_FEATURES="$FINAL_FEATURES,$FEATURE"
-        fi
-
-      # If changes related to other folders excpet tests, we also consider them as common part.
-      # The scope of PR testing is all test scripts.
-      else
-        FINAL_FEATURES=""
-        break
+    if [[ -n "$IMPACTED_TESTS" ]]; then
+      TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/categorize_test_scripts_by_topology.py --files "$IMPACTED_TESTS")
+      echo "Test scripts:"
+      echo "$TEST_SCRIPTS"
+      sudo apt-get -o DPkg::Lock::Timeout=600 -y install jq
+      PR_CHECKERS=$(echo "${TEST_SCRIPTS}" | jq -c 'keys')
+      rc=$?
+      echo "PR checkers:"
+      echo "$PR_CHECKERS"
+      if [[ $rc -ne 0 ]]; then
+        echo "##vso[task.complete result=Failed;]Get valid PR checkers fails."
+        exit 1
       fi
-    done
-
-    TEST_SCRIPTS=$(python ./.azure-pipelines/impacted_area_testing/get_test_scripts.py --features ${FINAL_FEATURES} --location tests)
-
-    if [[ $? -ne 0 ]]; then
-      echo "##vso[task.complete result=Failed;]Get test scripts fails."
-      exit 1
+    else
+      echo "No impacted tests found."
+      PR_CHECKERS="[]"
+      TEST_SCRIPTS="{}"
     fi
-
-    PR_CHECKERS=$(echo "${TEST_SCRIPTS}" | jq -c 'keys')
-
-    if [[ $? -ne 0 ]]; then
-      echo "##vso[task.complete result=Failed;]Get valid PR checkers fails."
-      exit 1
-    fi
-
     echo "##vso[task.setvariable variable=PR_CHECKERS;isOutput=true]$PR_CHECKERS"
     echo "##vso[task.setvariable variable=TEST_SCRIPTS;isOutput=true]$TEST_SCRIPTS"
+
   name: SetVariableTask
   continueOnError: false
   displayName: "Get impacted area"
