modify

diff --git a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
--- a/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
+++ b/.azure-pipelines/impacted_area_testing/get-impacted-area.yml
@@ -2,8 +2,15 @@ steps:
 - script: |
     set -x
 
-    DIFF_FOLDERS=$(git diff HEAD^ HEAD --name-only | xargs -n1 dirname | sort -u | tr '\n' ' ') || ""
-    echo -n "##vso[task.setvariable variable=DIFF_FOLDERS]$DIFF_FOLDERS"
+    DIFF_FOLDERS=$(git diff HEAD^ HEAD --name-only | xargs -n1 dirname | sort -u | tr '\n' ' ')
+
+    if [[ -z "$DIFF_FOLDERS" ]]; then
+      echo "##vso[task.complete result=Failed;]Get diff folders fail."
+      exit 1
+    else
+      echo -n "##vso[task.setvariable variable=DIFF_FOLDERS]$DIFF_FOLDERS"
+    fi
+  continueOnError: false
   displayName: "Get diff folders"
 
 - script: |
@@ -15,7 +22,6 @@ steps:
     sudo apt-get install -y jq
 
     FINAL_FEATURES=""
-    echo "$(DIFF_FOLDERS)"
     IFS=' ' read -ra FEATURES_LIST <<< "$(DIFF_FOLDERS)"
     for FEATURE in "${FEATURES_LIST[@]}"
     do
@@ -25,7 +31,12 @@ steps:
         break
 
       # If changes only limited to specific feature, the scope of PR testing is impacted area.
-      elif [[ "$FEATURE" =~ \/tests\/.+\/.+\.py$ ]]; then
+      elif [[ "$FEATURE" =~ tests\/* ]]; then
+        # Cut the feature path
+        if [[ $FEATURE == */*/* ]]; then
+            FEATURE=$(echo "$FEATURE" | cut -d'/' -f1-2)
+        fi
+
         if [[ -z "$FINAL_FEATURES" ]]; then
           FINAL_FEATURES="${FEATURE#tests/}"
         else
@@ -51,4 +62,5 @@ steps:
     echo "##vso[task.setvariable variable=PR_CHECKERS;isOutput=true]$PR_CHECKERS"
     echo "##vso[task.setvariable variable=TEST_SCRIPTS;isOutput=true]$TEST_SCRIPTS"
   name: SetVariableTask
+  continueOnError: false
   displayName: "Get impacted area"
