Update config

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -73,12 +73,10 @@ stages:
           exit 1
         fi
 
-  - job:
+  - job: t1_lag_classic
     pool: sonictest-t1-lag
-    displayName: "kvmtest-t1-lag"
+    displayName: "kvmtest-t1-lag classic"
     timeoutInMinutes: 360
-    condition: and(succeeded(), not(eq(variables.RUN_TEST_BY_SCHEDULER, 'YES')))
-
     steps:
     - template: .azure-pipelines/run-test-template.yml
       parameters:
@@ -88,15 +86,38 @@ stages:
         tbtype: t1-lag
         vmtype: ceos
 
-  - job:
-    displayName: "kvmtest-t1-lag by scheduler"
-    pool: sonictest
+  - job: t1_lag_testbedv2
+    displayName: "kvmtest-t1-lag by TestbedV2"
+    pool:
+      vmImage: 'ubuntu-20.04'
     timeoutInMinutes: 540
     condition: and(succeeded(), eq(variables.RUN_TEST_BY_SCHEDULER, 'YES'))
     steps:
     - template: .azure-pipelines/run-test-scheduler-template.yml
       parameters:
         TOPOLOGY: t1-lag
+
+  - job:
+    pool:
+      vmImage: 'ubuntu-20.04'
+    displayName: "kvmtest-t1-lag"
+    dependsOn:
+    - t1_lag_classic
+    - t1_lag_testbedv2
+    condition: always()
+    variables:
+      resultOfClassic: $[ dependencies.t1_lag_classic.result ]
+      resultOfTestbedV2: $[ dependencies.t1_lag_testbedv2.result ]
+
+    steps:
+    - script: |
+        if [ $(t1_lag_classic) == "Succeeded" ] || [ $(t1_lag_classic) == "Succeeded" ]; then
+          echo "One or both of t1_lag_classic and t1_lag_testbedv2 passed."
+          exit 0
+        else
+          echo "Both t1_lag_classic and t1_lag_testbedv2 failed! Please check the detailed information."
+          exit 1
+        fi
 
   - job:
     pool: sonictest-sonic-t0
