Revert back deleted jobs

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,15 +2,11 @@
 # Start with a minimal pipeline that you can customize to build and deploy your code.
 # Add steps that build, run tests, deploy, and more:
 # https://aka.ms/yaml
-
 pr:
 - master
-
 name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
-
 stages:
 - stage: Test
-
   variables:
   - name: inventory
     value: veos_vtb
@@ -19,7 +15,88 @@ stages:
   - group: GIT_SECRETS
 
   jobs:
+  - job: t0_part1
+    pool: sonictest
+    displayName: "kvmtest-t0-part1"
+    timeoutInMinutes: 360
+
+    steps:
+    - template: .azure-pipelines/run-test-template.yml
+      parameters:
+        dut: vlab-01
+        tbname: vms-kvm-t0
+        ptf_name: ptf_vms6-1
+        tbtype: t0
+        vmtype: ceos
+        section: part-1
+
+  - job: t0_part2
+    pool: sonictest
+    displayName: "kvmtest-t0-part2"
+    timeoutInMinutes: 360
+
+    steps:
+    - template: .azure-pipelines/run-test-template.yml
+      parameters:
+        dut: vlab-01
+        tbname: vms-kvm-t0
+        ptf_name: ptf_vms6-1
+        tbtype: t0
+        vmtype: ceos
+        section: part-2
+
   - job:
+    pool:
+      vmImage: 'ubuntu-20.04'
+    displayName: "kvmtest-t0"
+    dependsOn:
+    - t0_part1
+    - t0_part2
+    condition: always()
+    variables:
+      resultOfPart1: $[ dependencies.t0_part1.result ]
+      resultOfPart2: $[ dependencies.t0_part2.result ]
+
+    steps:
+    - script: |
+        if [ $(resultOfPart1) == "Succeeded" ] && [ $(resultOfPart2) == "Succeeded" ]; then
+          echo "Both job kvmtest-t0-part1 and kvmtest-t0-part2 are passed."
+          exit 0
+        else
+          echo "Either job kvmtest-t0-part1 or job kvmtest-t0-part2 failed! Please check the detailed information."
+          exit 1
+        fi
+  - job:
+    pool: sonictest-t1-lag
+    displayName: "kvmtest-t1-lag"
+    timeoutInMinutes: 360
+
+    steps:
+    - template: .azure-pipelines/run-test-template.yml
+      parameters:
+        dut: vlab-03
+        tbname: vms-kvm-t1-lag
+        ptf_name: ptf_vms6-2
+        tbtype: t1-lag
+        vmtype: ceos
+
+  - job:
+    pool: sonictest-sonic-t0
+    displayName: "kvmtest-t0-sonic"
+    timeoutInMinutes: 360
+
+    steps:
+    - template: .azure-pipelines/run-test-template.yml
+      parameters:
+        dut: vlab-02
+        tbname: vms-kvm-t0-64-32
+        ptf_name: ptf_vms6-1
+        tbtype: t0-sonic
+        vmtype: vsonic
+
+  - job:
+    pool: sonictest-dualtor
+    displayName: "kvmtest-dualtor"
     pool: sonictest-ma
     displayName: "kvmtest-multi-asic"
     timeoutInMinutes: 360
@@ -27,9 +104,13 @@ stages:
     steps:
       - template: .azure-pipelines/run-test-template.yml
         parameters:
+          dut: all
+          tbname: vms-kvm-dual-t0
+          ptf_name: ptf-04
+          tbtype: dualtor
           dut: vlab-08
           tbname: vms-kvm-four-asic-t1-lag
           ptf_name: ptf_vms6-4
           tbtype: multi-asic-t1-lag-pr
           vmtype: ceos
-          image: sonic-4asic-vs.img.gz
+          image: sonic-4asic-vs.img.gz 
