add a step to extract t2 pr checker script list

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -314,6 +314,23 @@ stages:
     continueOnError: true
     pool: sonic-ubuntu-1c
     steps:
+      - script: |
+          set -x
+
+          sudo apt-get -o DPkg::Lock::Timeout=600 update && sudo apt-get -o DPkg::Lock::Timeout=600 -y install jq
+
+          echo "$TEST_SCRIPTS" > /tmp/ts.json
+          echo "TEST_SCRIPTS value from file:"
+          cat /tmp/ts.json
+          TEST_SCRIPTS=$(jq -r -c '."${{ parameters.TOPOLOGY }}_checker"' /tmp/ts.json)
+          rm /tmp/ts.json
+          if [[ -z "$TEST_SCRIPTS" ]]; then
+            echo "##vso[task.complete result=Failed;]Get test scripts of specfic topology fails."
+            exit 1
+          fi
+          SCRIPTS=$(echo "$TEST_SCRIPTS" | jq -r '. | join(",")')
+          echo -n "##vso[task.setvariable variable=SCRIPTS]$SCRIPTS"
+        displayName: "Get ${{ parameters.TOPOLOGY }} test scripts"
 
       - template: .azure-pipelines/run-test-elastictest-template.yml
         parameters:
