Refine cancel logic, enable other test pipeline, and add more information

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,57 +21,57 @@ stages:
   - group: GIT_SECRETS
 
   jobs:
-  # - job: t0_part1
-  #   pool: sonictest
-  #   displayName: "kvmtest-t0-part1"
-  #   timeoutInMinutes: 360
+   - job: t0_part1
+     pool: sonictest
+     displayName: "kvmtest-t0-part1"
+     timeoutInMinutes: 360
 
-  #   steps:
-  #   - template: .azure-pipelines/run-test-template.yml
-  #     parameters:
-  #       dut: vlab-01
-  #       tbname: vms-kvm-t0
-  #       ptf_name: ptf_vms6-1
-  #       tbtype: t0
-  #       vmtype: ceos
-  #       section: part-1
+     steps:
+     - template: .azure-pipelines/run-test-template.yml
+       parameters:
+         dut: vlab-01
+         tbname: vms-kvm-t0
+         ptf_name: ptf_vms6-1
+         tbtype: t0
+         vmtype: ceos
+         section: part-1
 
-  # - job: t0_part2
-  #   pool: sonictest
-  #   displayName: "kvmtest-t0-part2"
-  #   timeoutInMinutes: 360
+   - job: t0_part2
+     pool: sonictest
+     displayName: "kvmtest-t0-part2"
+     timeoutInMinutes: 360
 
-  #   steps:
-  #   - template: .azure-pipelines/run-test-template.yml
-  #     parameters:
-  #       dut: vlab-01
-  #       tbname: vms-kvm-t0
-  #       ptf_name: ptf_vms6-1
-  #       tbtype: t0
-  #       vmtype: ceos
-  #       section: part-2
+     steps:
+     - template: .azure-pipelines/run-test-template.yml
+       parameters:
+         dut: vlab-01
+         tbname: vms-kvm-t0
+         ptf_name: ptf_vms6-1
+         tbtype: t0
+         vmtype: ceos
+         section: part-2
 
-  # - job:
-  #   pool:
-  #     vmImage: 'ubuntu-20.04'
-  #   displayName: "kvmtest-t0"
-  #   dependsOn:
-  #   - t0_part1
-  #   - t0_part2
-  #   condition: always()
-  #   variables:
-  #     resultOfPart1: $[ dependencies.t0_part1.result ]
-  #     resultOfPart2: $[ dependencies.t0_part2.result ]
+   - job:
+     pool:
+       vmImage: 'ubuntu-20.04'
+     displayName: "kvmtest-t0"
+     dependsOn:
+     - t0_part1
+     - t0_part2
+     condition: always()
+     variables:
+       resultOfPart1: $[ dependencies.t0_part1.result ]
+       resultOfPart2: $[ dependencies.t0_part2.result ]
 
-  #   steps:
-  #   - script: |
-  #       if [ $(resultOfPart1) == "Succeeded" ] && [ $(resultOfPart2) == "Succeeded" ]; then
-  #         echo "Both job kvmtest-t0-part1 and kvmtest-t0-part2 are passed."
-  #         exit 0
-  #       else
-  #         echo "Either job kvmtest-t0-part1 or job kvmtest-t0-part2 failed! Please check the detailed information."
-  #         exit 1
-  #       fi
+     steps:
+     - script: |
+         if [ $(resultOfPart1) == "Succeeded" ] && [ $(resultOfPart2) == "Succeeded" ]; then
+           echo "Both job kvmtest-t0-part1 and kvmtest-t0-part2 are passed."
+           exit 0
+         else
+           echo "Either job kvmtest-t0-part1 or job kvmtest-t0-part2 failed! Please check the detailed information."
+           exit 1
+         fi
 
   - job:
     pool: sonictest
@@ -98,45 +98,45 @@ stages:
       parameters:
         TOPOLOGY: t1-lag
 
-  # - job:
-  #   pool: sonictest-sonic-t0
-  #   displayName: "kvmtest-t0-sonic"
-  #   timeoutInMinutes: 360
+   - job:
+     pool: sonictest-sonic-t0
+     displayName: "kvmtest-t0-sonic"
+     timeoutInMinutes: 360
 
-  #   steps:
-  #   - template: .azure-pipelines/run-test-template.yml
-  #     parameters:
-  #       dut: vlab-02
-  #       tbname: vms-kvm-t0-64-32
-  #       ptf_name: ptf_vms6-1
-  #       tbtype: t0-sonic
-  #       vmtype: vsonic
+     steps:
+     - template: .azure-pipelines/run-test-template.yml
+       parameters:
+         dut: vlab-02
+         tbname: vms-kvm-t0-64-32
+         ptf_name: ptf_vms6-1
+         tbtype: t0-sonic
+         vmtype: vsonic
 
-  # - job:
-  #   pool: sonictest-dualtor
-  #   displayName: "kvmtest-dualtor"
-  #   timeoutInMinutes: 360
+   - job:
+     pool: sonictest-dualtor
+     displayName: "kvmtest-dualtor"
+     timeoutInMinutes: 360
 
-  #   steps:
-  #     - template: .azure-pipelines/run-test-template.yml
-  #       parameters:
-  #         dut: all
-  #         tbname: vms-kvm-dual-t0
-  #         ptf_name: ptf-04
-  #         tbtype: dualtor
-  #         vmtype: ceos
+     steps:
+       - template: .azure-pipelines/run-test-template.yml
+         parameters:
+           dut: all
+           tbname: vms-kvm-dual-t0
+           ptf_name: ptf-04
+           tbtype: dualtor
+           vmtype: ceos
 
-  # - job:
-  #   pool: sonictest-ma
-  #   displayName: "kvmtest-multi-asic-t1-lag"
-  #   timeoutInMinutes: 360
+   - job:
+     pool: sonictest-ma
+     displayName: "kvmtest-multi-asic-t1-lag"
+     timeoutInMinutes: 360
 
-  #   steps:
-  #     - template: .azure-pipelines/run-test-template.yml
-  #       parameters:
-  #         dut: vlab-08
-  #         tbname: vms-kvm-four-asic-t1-lag
-  #         ptf_name: ptf_vms6-4
-  #         tbtype: multi-asic-t1-lag-pr
-  #         vmtype: ceos
-  #         image: sonic-4asic-vs.img.gz
+     steps:
+       - template: .azure-pipelines/run-test-template.yml
+         parameters:
+           dut: vlab-08
+           tbname: vms-kvm-four-asic-t1-lag
+           ptf_name: ptf_vms6-4
+           tbtype: multi-asic-t1-lag-pr
+           vmtype: ceos
+           image: sonic-4asic-vs.img.gz
