Revert "Updated with master"
This reverts commit c1ef4c7cd8aba14af027dc052fdb6c75a00c5a74, reversing
changes made to c4949cc77e2004774714623db549e392a85cc197.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -3,13 +3,8 @@
 # Add steps that build, run tests, deploy, and more:
 # https://aka.ms/yaml
 
-# For every job:
-# continueOnError: false means it's a required test job and will block merge if it fails
-# continueOnError: true means it's an optional test job and will not block merge even though it fails(unless a required test job depends on its result)
-
 pr:
 - master
-trigger: none
 
 name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
 
@@ -17,7 +12,6 @@ stages:
 - stage: Test
 
   variables:
-  - group: Testbed-Tools
   - name: inventory
     value: veos_vtb
   - name: testbed_file
@@ -25,19 +19,11 @@ stages:
   - group: GIT_SECRETS
 
   jobs:
-  - job: pre_commit
-    displayName: "pre-commit-check"
-    timeoutInMinutes: 10
-    continueOnError: true
-    steps:
-    - template: .azure-pipelines/pre-commit-check.yml
-
   - job: t0_part1
     pool: sonictest
     displayName: "kvmtest-t0-part1"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: false
+    timeoutInMinutes: 360
+
     steps:
     - template: .azure-pipelines/run-test-template.yml
       parameters:
@@ -51,9 +37,8 @@ stages:
   - job: t0_part2
     pool: sonictest
     displayName: "kvmtest-t0-part2"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: false
+    timeoutInMinutes: 360
+
     steps:
     - template: .azure-pipelines/run-test-template.yml
       parameters:
@@ -64,32 +49,6 @@ stages:
         vmtype: ceos
         section: part-2
 
-  - job: t0_testbedv2
-    displayName: "kvmtest-t0 by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-    - template: .azure-pipelines/run-test-scheduler-template.yml
-      parameters:
-        TOPOLOGY: t0
-        MIN_WORKER: $(T0_INSTANCE_NUM)
-        MAX_WORKER: $(T0_INSTANCE_NUM)
-
-  - job: t0_2vlans_testbedv2
-    displayName: "kvmtest-t0-2vlans by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-    - template: .azure-pipelines/run-test-scheduler-template.yml
-      parameters:
-        TOPOLOGY: t0
-        TEST_SET: t0-2vlans
-        MIN_WORKER: $(T0_2VLANS_INSTANCE_NUM)
-        MAX_WORKER: $(T0_2VLANS_INSTANCE_NUM)
-        DEPLOY_MG_EXTRA_PARAMS: "-e vlan_config=two_vlan_a"
-
   - job:
     pool:
       vmImage: 'ubuntu-20.04'
@@ -97,38 +56,26 @@ stages:
     dependsOn:
     - t0_part1
     - t0_part2
-    - t0_testbedv2
-    - t0_2vlans_testbedv2
     condition: always()
-    continueOnError: false
     variables:
       resultOfPart1: $[ dependencies.t0_part1.result ]
       resultOfPart2: $[ dependencies.t0_part2.result ]
-      resultOfT0TestbedV2: $[ dependencies.t0_testbedv2.result ]
-      resultOfT02VlansTestbedV2: $[ dependencies.t0_2vlans_testbedv2.result ]
 
     steps:
     - script: |
-        if [ $(resultOfT0TestbedV2) == "Succeeded" ] && [ $(resultOfT02VlansTestbedV2) == "Succeeded" ]; then
-          echo "TestbedV2 t0 passed."
-          exit 0
-        fi
-
         if [ $(resultOfPart1) == "Succeeded" ] && [ $(resultOfPart2) == "Succeeded" ]; then
-          echo "Classic t0 jobs(both part1 and part2) passed."
+          echo "Both job kvmtest-t0-part1 and kvmtest-t0-part2 are passed."
           exit 0
+        else
+          echo "Either job kvmtest-t0-part1 or job kvmtest-t0-part2 failed! Please check the detailed information."
+          exit 1
         fi
 
-        echo "Both classic and TestbedV2 t0 jobs failed! Please check the detailed information. (Any of them passed, t0 will be considered as passed)"
-        exit 1
-
-
-  - job: t1_lag_classic
+  - job:
     pool: sonictest-t1-lag
-    displayName: "kvmtest-t1-lag classic"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: false
+    displayName: "kvmtest-t1-lag"
+    timeoutInMinutes: 360
+
     steps:
     - template: .azure-pipelines/run-test-template.yml
       parameters:
@@ -138,44 +85,11 @@ stages:
         tbtype: t1-lag
         vmtype: ceos
 
-  - job: t1_lag_testbedv2
-    displayName: "kvmtest-t1-lag by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-    - template: .azure-pipelines/run-test-scheduler-template.yml
-      parameters:
-        TOPOLOGY: t1-lag
-        MIN_WORKER: $(T1_LAG_INSTANCE_NUM)
-        MAX_WORKER: $(T1_LAG_INSTANCE_NUM)
-
-  - job:
-    displayName: "kvmtest-t1-lag"
-    dependsOn:
-    - t1_lag_classic
-    - t1_lag_testbedv2
-    condition: always()
-    continueOnError: false
-    variables:
-      resultOfClassic: $[ dependencies.t1_lag_classic.result ]
-      resultOfTestbedV2: $[ dependencies.t1_lag_testbedv2.result ]
-    steps:
-    - script: |
-        if [ $(resultOfClassic) == "Succeeded" ] || [ $(resultOfTestbedV2) == "Succeeded" ]; then
-          echo "One or both of t1_lag_classic and t1_lag_testbedv2 passed."
-          exit 0
-        else
-          echo "Both t1_lag_classic and t1_lag_testbedv2 failed! Please check the detailed information."
-          exit 1
-        fi
-
   - job:
     pool: sonictest-sonic-t0
     displayName: "kvmtest-t0-sonic"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: true
+    timeoutInMinutes: 360
+
     steps:
     - template: .azure-pipelines/run-test-template.yml
       parameters:
@@ -185,29 +99,11 @@ stages:
         tbtype: t0-sonic
         vmtype: vsonic
 
-  - job: sonic_t0_testbedv2
-    displayName: "kvmtest-t0-sonic by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-      - template: .azure-pipelines/run-test-scheduler-template.yml
-        parameters:
-          TOPOLOGY: t0-64-32
-          MIN_WORKER: $(T0_SONIC_INSTANCE_NUM)
-          MAX_WORKER: $(T0_SONIC_INSTANCE_NUM)
-          TEST_SET: t0-sonic
-          COMMON_EXTRA_PARAMS: "--neighbor_type=sonic --enable_macsec --macsec_profile=128_SCI,256_XPN_SCI"
-          VM_TYPE: vsonic
-          SPECIFIED_PARAMS: '{\"test_pretest.py\":[\"--completeness_level=confident\",\"--allow_recover\"],\"test_posttest.py\":[\"--completeness_level=confident\",\"--allow_recover\"]}'
-
-
   - job:
     pool: sonictest-dualtor
     displayName: "kvmtest-dualtor"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: false
+    timeoutInMinutes: 360
+
     steps:
       - template: .azure-pipelines/run-test-template.yml
         parameters:
@@ -216,59 +112,3 @@ stages:
           ptf_name: ptf-04
           tbtype: dualtor
           vmtype: ceos
-
-  - job: dualtor_testbedv2
-    displayName: "kvmtest-dualtor-t0 by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-      - template: .azure-pipelines/run-test-scheduler-template.yml
-        parameters:
-          TOPOLOGY: dualtor
-          MIN_WORKER: $(T0_DUALTOR_INSTANCE_NUM)
-          MAX_WORKER: $(T0_DUALTOR_INSTANCE_NUM)
-          COMMON_EXTRA_PARAMS: "--disable_loganalyzer "
-
-  - job:
-    pool: sonictest-ma
-    displayName: "kvmtest-multi-asic-t1-lag"
-    timeoutInMinutes: 400
-    condition: and(succeeded(), eq(variables.RUN_CLASSICAL_TEST, 'YES'))
-    continueOnError: false
-    steps:
-      - template: .azure-pipelines/run-test-template.yml
-        parameters:
-          dut: vlab-08
-          tbname: vms-kvm-four-asic-t1-lag
-          ptf_name: ptf_vms6-4
-          tbtype: multi-asic-t1-lag-pr
-          vmtype: ceos
-          image: sonic-4asic-vs.img.gz
-
-  - job: multi_asic_testbedv2
-    displayName: "kvmtest-multi-asic-t1-lag by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-      - template: .azure-pipelines/run-test-scheduler-template.yml
-        parameters:
-          TOPOLOGY: t1-8-lag
-          TEST_SET: multi-asic-t1-lag
-          MIN_WORKER: $(MULTI_ASIC_INSTANCE_NUM)
-          MAX_WORKER: $(MULTI_ASIC_INSTANCE_NUM)
-          NUM_ASIC: 4
-
-  - job: wan_testbedv2
-    displayName: "kvmtest-wan by TestbedV2"
-    timeoutInMinutes: 240
-    condition: and(succeeded(), eq(variables.RUN_TESTBEDV2_TEST, 'YES'))
-    continueOnError: false
-    steps:
-      - template: .azure-pipelines/run-test-scheduler-template.yml
-        parameters:
-          TOPOLOGY: wan-pub
-          MIN_WORKER: $(WAN_INSTANCE_NUM)
-          MAX_WORKER: $(WAN_INSTANCE_NUM)
-          COMMON_EXTRA_PARAMS: "--skip_sanity "
