Merged PR 6143: Update lock/release testbed not to use CLIENT secret
Update lock/release testbed not to use CLIENT secret

This is part of the security wave 1 effort for eliminating CLIENT secrets.
The lock_release.py script used for lock/release testbed has been improved to get ACCESS_TOKEN from environment variable.

All the pipeline yaml steps calling lock_release.py has been updated from a script task to AzureCLI task which is capable of getting access_token using service connection "SONiC-Automation".

The "SONiC-Automation" service connection is associated with a user managed identity "SONiC-Automation-umi".

The user managed identity is authorized for accessing various Azure resources used by nightly tests.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>

diff --git a/.azure-pipelines/sonic-metadata/metadata_upgrade_template.yml b/.azure-pipelines/sonic-metadata/metadata_upgrade_template.yml
--- a/.azure-pipelines/sonic-metadata/metadata_upgrade_template.yml
+++ b/.azure-pipelines/sonic-metadata/metadata_upgrade_template.yml
@@ -121,23 +121,33 @@ stages:
           print('##vso[task.setvariable variable=TOPOLOGY_TYPE;]{}'.format(target_testbed['topo']['type']))
           print('##vso[task.setvariable variable=DUT_LIST;]{}'.format(dut_list_str))
 
-    - script: |
-        set -ex
-        TIMEOUT=7200
-        INTERVAL=60
-        wait_time=0
-        until python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock -r UpgradePathAZP -o 48; do
-            if (( $wait_time >= $TIMEOUT )); then
-                echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
-                exit 1
-            fi
-            echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
-            sleep $INTERVAL
-            wait_time=$(expr $wait_time + $INTERVAL)
-        done
-        echo "##vso[task.setvariable variable=TESTBED_LOCKED]Yes"
-      env:
-        ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
+    - task: AzureCLI@2
+      inputs:
+        azureSubscription: "SONiC-Automation"
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          pwd
+
+          accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+          export ACCESS_TOKEN=$accessToken
+
+          set -e
+
+          TIMEOUT=7200
+          INTERVAL=60
+          wait_time=0
+          until python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock -r UpgradePathAZP -o 48; do
+
+              if (( $wait_time >= $TIMEOUT )); then
+                  echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
+                  exit 1
+              fi
+              echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
+              sleep $INTERVAL
+              wait_time=$(expr $wait_time + $INTERVAL)
+          done
+          echo "##vso[task.setvariable variable=TESTBED_LOCKED]Yes"
       displayName: Lock Testbed
       condition: eq('${{ parameters.SKIP_LOCKING_TESTBED }}', 'false')
 
@@ -254,9 +264,17 @@ stages:
           http_proxy='' https_proxy='' ./testbed-cli.sh -k ceos add-topo ${{ parameters.TESTBED_NAME }} password.txt
       condition: and(eq(variables['TESTBED_LOCKED'], 'Yes'), eq('${{ parameters.VM_TYPE }}', 'vsonic'))
 
-    - script: |
-        python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a release
-      env:
-        ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
+    - task: AzureCLI@2
+      inputs:
+        azureSubscription: "SONiC-Automation"
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          pwd
+
+          accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+          export ACCESS_TOKEN=$accessToken
+
+          python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a release
       displayName: Release Testbed
       condition: eq('${{ parameters.SKIP_LOCKING_TESTBED }}', 'false')
