Merged PR 3806: Exit pipeline early when duthosts fixture failed
Exit pipeline early when duthosts fixture failed

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

Cherry picked from !3803

diff --git a/.azure-pipelines/nightly/templates/nightly_test.yml b/.azure-pipelines/nightly/templates/nightly_test.yml
--- a/.azure-pipelines/nightly/templates/nightly_test.yml
+++ b/.azure-pipelines/nightly/templates/nightly_test.yml
@@ -462,6 +462,9 @@ stages:
                 elif [[ $RUN_TESTS_RC == 10 ]]; then
                   echo "Sanity check failed. Please check the detailed log."
                   exit 1
+                elif [[ $RUN_TESTS_RC == 15 ]]; then
+                  echo "duthosts fixture failed. Please check the detailed log."
+                  exit 1
                 else
                   exit 0
                 fi
