Merged PR 570: Exit with 65 code for pretest failure and fail nightly pipeline
Exit with 65 code for pretest failure and fail nightly pipeline.
user-defined exit codes is the range 64 - 113.

Please check the test pipeline result for pretest failed.
https://dev.azure.com/mssonic/internal/_build/results?buildId=101385&view=logs&j=bed026c5-b179-58e8-339f-77f4b7309744&t=21d603e6-69b8-528a-d690-b3ff2c012ba1

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

diff --git a/.azure-pipelines/nightly/templates/nightly_test.yml b/.azure-pipelines/nightly/templates/nightly_test.yml
--- a/.azure-pipelines/nightly/templates/nightly_test.yml
+++ b/.azure-pipelines/nightly/templates/nightly_test.yml
@@ -308,7 +308,12 @@ stages:
                     -r \
                     ${{ parameters.TESTBED_SPECIFIC }} \
                     -e "$PARAMS"
-                exit 0
+                if [[ $? == 65 ]]; then
+                  echo "pretest failed. Please check the detailed log."
+                  exit 1
+                else
+                  exit 0
+                fi
             env:
               PY_SAITHRIFT_URL: ${{ parameters.PY_SAITHRIFT_URL }}
               PTF_PORTMAP: ${{ parameters.PTF_PORTMAP }}
