Merged PR 778: Try to redeploy topology if restart-ptf failed in nightly test
Try to redeploy topology if restart-ptf failed in nightly test

Recently we frequently hit the issue of restart-ptf failure in nightly test.
The reason is that some testbed topology was broken. The cEOS docker
containers and their associated ovs bridges are gone. When this issue happens,
'testbed-cli.sh remove-topo' will fail too.
PR https://github.com/Azure/sonic-mgmt/pull/6020 improved the robustness of
'testbed-cli.sh remove-topo' for such scenario. With the help of that change,
then we can improve the nightly test to run a 'remove-topo' and 'add-topo'
if 'restart-ptf' failed.

PR https://github.com/Azure/sonic-mgmt/pull/5945 introduced a new testbed-cli.sh
command 'redeploy-topo' which is a wrapper for 'remove-topo' and 'add-topo'.

So, in this change, we can run 'testbed-cli.sh redeploy-topo' if restart-ptf failed.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>

diff --git a/.azure-pipelines/nightly/templates/nightly_test.yml b/.azure-pipelines/nightly/templates/nightly_test.yml
--- a/.azure-pipelines/nightly/templates/nightly_test.yml
+++ b/.azure-pipelines/nightly/templates/nightly_test.yml
@@ -256,7 +256,7 @@ stages:
             inputs:
               targetType: 'inline'
               script: |
-                set -ex
+                set -x
 
                 if [[ ${{ parameters.ENABLE_DATAACL }} == True ]]; then
                     CONFIG_PARAMS="$CONFIG_PARAMS -e enable_data_plane_acl=true"
@@ -266,7 +266,12 @@ stages:
                 cd ansible
 
                 http_proxy='' https_proxy='' ./testbed-cli.sh restart-ptf ${{ parameters.TESTBED_NAME }} password.txt -e ptf_imagetag=internal
-                http_proxy='' https_proxy='' ./testbed-cli.sh deploy-mg ${{ parameters.TESTBED_NAME }} $(INVENTORY_NAME) password.txt $CONFIG_PARAMS
+                # If restart-ptf failed, try to redeploy the topology
+                if [[ $? != 0 ]]; then
+                    http_proxy='' https_proxy='' ./testbed-cli.sh redeploy-topo ${{ parameters.TESTBED_NAME }} password.txt -e ptf_imagetag=internal
+                fi
+
+                http_proxy='' https_proxy='' ./testbed-cli.sh deploy-mg ${{ parameters.TESTBED_NAME }} $(INVENTORY_NAME) password.txt $CONFIG_PARAMS || exit 1
                 sleep 180
 
           - task: Bash@3
