Merged PR 6143: Update lock/release testbed not to use CLIENT secret
Update lock/release testbed not to use CLIENT secret

This is part of the security wave 1 effort for eliminating CLIENT secrets.
The lock_release.py script used for lock/release testbed has been improved to get ACCESS_TOKEN from environment variable.

All the pipeline yaml steps calling lock_release.py has been updated from a script task to AzureCLI task which is capable of getting access_token using service connection "SONiC-Automation".

The "SONiC-Automation" service connection is associated with a user managed identity "SONiC-Automation-umi".

The user managed identity is authorized for accessing various Azure resources used by nightly tests.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>

diff --git a/.azure-pipelines/metadata_scripts/run_metadata_test_template.yml b/.azure-pipelines/metadata_scripts/run_metadata_test_template.yml
--- a/.azure-pipelines/metadata_scripts/run_metadata_test_template.yml
+++ b/.azure-pipelines/metadata_scripts/run_metadata_test_template.yml
@@ -168,23 +168,32 @@ stages:
                 print('##vso[task.setvariable variable=TOPOLOGY_TYPE;]{}'.format(target_testbed['topo']['type']))
                 print('##vso[task.setvariable variable=DUT_LIST;]{}'.format(dut_list_str))
 
-          - script: |
-              TIMEOUT=7200
-              INTERVAL=60
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "SONiC-Automation"
+              scriptType: 'bash'
+              scriptLocation: 'inlineScript'
+              inlineScript: |
+                pwd
 
-              wait_time=0
-              cd sonic-mgmt-int
-              until python ./.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock; do
-                  if (( $wait_time >= $TIMEOUT)); then
-                      echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
-                      exit 1
-                  fi
-                  echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
-                  sleep $INTERVAL
-                  wait_time=$(expr $wait_time + $INTERVAL)
-              done
-            env:
-              ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
+                accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+                export ACCESS_TOKEN=$accessToken
+
+                TIMEOUT=7200
+                INTERVAL=60
+
+                wait_time=0
+                cd sonic-mgmt-int
+                until python ./.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock; do
+
+                    if (( $wait_time >= $TIMEOUT)); then
+                        echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
+                        exit 1
+                    fi
+                    echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
+                    sleep $INTERVAL
+                    wait_time=$(expr $wait_time + $INTERVAL)
+                done
             displayName: Lock Testbed
 
           - task: Bash@3
@@ -429,22 +438,31 @@ stages:
               searchFolder: '$(system.defaultworkingdirectory)/sonic-mgmt-int'
             condition: always()
 
-          - script: |
-              TIMEOUT=300
-              INTERVAL=60
+          - task: AzureCLI@2
+            inputs:
+              azureSubscription: "SONiC-Automation"
+              scriptType: 'bash'
+              scriptLocation: 'inlineScript'
+              inlineScript: |
+                pwd
 
-              wait_time=0
-              until python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a release; do
-                  if (( $wait_time >= $TIMEOUT)); then
-                      echo "Failed to release testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
-                      exit 1
-                  fi
-                  echo "Release testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
-                  sleep $INTERVAL
-                  wait_time=$(expr $wait_time + $INTERVAL)
-              done
-            env:
-              ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
+                accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+                export ACCESS_TOKEN=$accessToken
+
+                TIMEOUT=300
+                INTERVAL=60
+
+                wait_time=0
+                until python ./sonic-mgmt-int/.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a release; do
+
+                    if (( $wait_time >= $TIMEOUT)); then
+                        echo "Failed to release testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
+                        exit 1
+                    fi
+                    echo "Release testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
+                    sleep $INTERVAL
+                    wait_time=$(expr $wait_time + $INTERVAL)
+                done
             displayName: Release Testbed
             condition: always()
 
diff --git a/.azure-pipelines/sai_qualify/templates/sai_test.yml b/.azure-pipelines/sai_qualify/templates/sai_test.yml
--- a/.azure-pipelines/sai_qualify/templates/sai_test.yml
+++ b/.azure-pipelines/sai_qualify/templates/sai_test.yml
@@ -263,23 +263,31 @@ jobs:
           TESTBED_FILE: ${{ parameters.TESTBED_FILE }}
           BUILD_ID: $(Build.BuildId)
 
-      - script: |
-          TIMEOUT=600
-          INTERVAL=60
+      - task: AzureCLI@2
+        inputs:
+          azureSubscription: "SONiC-Automation"
+          scriptType: 'bash'
+          scriptLocation: 'inlineScript'
+          inlineScript: |
+            pwd
 
-          wait_time=0
-          until python ./.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock -o ${{ parameters.TESTBED_LOCK_HOUR }} -r "${{ parameters.LOCK_TESTBED_REASON }}" -f no; do
-              if (( $wait_time >= $TIMEOUT)); then
-                  echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
-                  exit 1
-              fi
-              echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
-              sleep $INTERVAL
-              wait_time=$(expr $wait_time + $INTERVAL)
-          done
+            accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+            export ACCESS_TOKEN=$accessToken
 
-        env:
-          ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
+            TIMEOUT=600
+            INTERVAL=60
+
+            wait_time=0
+            until python ./.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a lock -o ${{ parameters.TESTBED_LOCK_HOUR }} -r "${{ parameters.LOCK_TESTBED_REASON }}" -f no; do
+
+                if (( $wait_time >= $TIMEOUT)); then
+                    echo "Failed to lock testbed ${{ parameters.TESTBED_NAME }} after retrying for $TIMEOUT seconds with interval $INTERVAL"
+                    exit 1
+                fi
+                echo "Lock testbed ${{ parameters.TESTBED_NAME }} failed, wait $INTERVAL seconds to retry"
+                sleep $INTERVAL
+                wait_time=$(expr $wait_time + $INTERVAL)
+            done
         condition: ${{ parameters.LOCK_TESTBED }}
         displayName: Lock Testbed
 
@@ -922,17 +930,20 @@ jobs:
           INVENTORY_NAME: $(INVENTORY_NAME)
           ENABLE_DATAACL: ${{ parameters.ENABLE_DATAACL }}
 
-      - task: Bash@3
+      - task: AzureCLI@2
         condition: and(${{ parameters.LOCK_TESTBED }}, eq(variables.TESTBED_LOCKED, 'locked'))
         displayName: Release Testbed
         inputs:
-          targetType: 'inline'
-          script: |
-            set -x
+          azureSubscription: "SONiC-Automation"
+          scriptType: 'bash'
+          scriptLocation: 'inlineScript'
+          inlineScript: |
+            pwd
+
+            accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
+            export ACCESS_TOKEN=$accessToken
 
             python ./.azure-pipelines/nightly/templates/lock_release.py -t ${{ parameters.TESTBED_NAME }} -a release
-        env:
-          ELASTICTEST_MSAL_SECRET_VALUE: $(ELASTICTEST_MSAL_SECRET_VALUE)
 
       - task: Bash@3
         displayName: Upload Test Results
