Update cont-warmboot.yml for Azure Pipelines

diff --git a/tests/pipelines/cont-warmboot.yml b/tests/pipelines/cont-warmboot.yml
--- a/tests/pipelines/cont-warmboot.yml
+++ b/tests/pipelines/cont-warmboot.yml
@@ -107,24 +107,24 @@ stages:
 
               if [ "${PIPESTATUS[0]}" -ne "0" ]; then
                   # fail and stop all the remaining batches if pytest fails
-                  echo "Batch iteration ${iteration}+ failed"
+                  echo "Iteration ${iteration} failed. Cancel subsequent tests, and saving KVM memdmp"
                   docker exec sonic-mgmt bash -c "$LOG_CMD"
                   echo "##vso[task.setvariable variable=continue]false"
 
-                  # save dut state if test fails
-                  virsh_version=$(virsh --version)
-                  if [ $virsh_version == "6.0.0" ]; then
-                      mkdir -p $(Build.ArtifactStagingDirectory)/kvmdump
-                      virsh -c qemu:///system list
-                      virsh -c qemu:///system save $(dut) $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).memdmp
-                      virsh -c qemu:///system dumpxml $(dut) > $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).xml
-                      img=$(virsh -c qemu:///system domblklist $(dut) | grep vda | awk '{print $2}')
-                      cp $img $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).img
-                      virsh -c qemu:///system undefine $(dut)
-                  fi
-                  docker commit $(ptf_name) docker-ptf:$(Build.BuildNumber)
-                  docker save docker-ptf:$(Build.BuildNumber) | gzip -c > $(Build.ArtifactStagingDirectory)/kvmdump/docker-ptf-dump.gz
-                  docker rmi docker-ptf:$(Build.BuildNumber)
+                  # # save dut state if test fails
+                  # virsh_version=$(virsh --version)
+                  # if [ $virsh_version == "6.0.0" ]; then
+                  #     mkdir -p $(Build.ArtifactStagingDirectory)/kvmdump
+                  #     virsh -c qemu:///system list
+                  #     virsh -c qemu:///system save $(dut) $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).memdmp
+                  #     virsh -c qemu:///system dumpxml $(dut) > $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).xml
+                  #     img=$(virsh -c qemu:///system domblklist $(dut) | grep vda | awk '{print $2}')
+                  #     cp $img $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).img
+                  #     virsh -c qemu:///system undefine $(dut)
+                  # fi
+                  # docker commit $(ptf_name) docker-ptf:$(Build.BuildNumber)
+                  # docker save docker-ptf:$(Build.BuildNumber) | gzip -c > $(Build.ArtifactStagingDirectory)/kvmdump/docker-ptf-dump.gz
+                  # docker rmi docker-ptf:$(Build.BuildNumber)
               fi
               docker exec sonic-mgmt bash -c "$LOG_CMD"
               cp -r /data/sonic-mgmt/tests/logs $(Build.ArtifactStagingDirectory)/
@@ -134,6 +134,7 @@ stages:
               echo "================ iteration ${iteration} completed==================="
           else
               echo "Test execution failure caused skipping of remaining tests"
+              exit 2
           fi
         displayName: "Run continuous warmboot tests"
         continueOnError: true
@@ -141,7 +142,6 @@ stages:
       - publish: $(Build.ArtifactStagingDirectory)/logs/continous_reboot_*
         artifact: sonic-buildimage.kvmtest.log@$(System.JobAttempt)
         displayName: "Archive sonic kvm logs"
-        condition: succeededOrFailed()
         continueOnError: true
 
 
