Update cont-warmboot.yml for Azure Pipelines

diff --git a/tests/pipelines/cont-warmboot.yml b/tests/pipelines/cont-warmboot.yml
--- a/tests/pipelines/cont-warmboot.yml
+++ b/tests/pipelines/cont-warmboot.yml
@@ -21,6 +21,11 @@ resources:
     name: Azure/sonic-mgmt
     endpoint: build
 
+parameters:
+- name: iterations 
+  type: object
+  default: [1,2,3,4,5,6,7,8,9,10] 
+
 stages:
 - stage: Test
   pool: sonictest
@@ -66,123 +71,105 @@ stages:
         # docker exec sonic-mgmt bash -c "pushd /data/sonic-mgmt/ansible;./testbed-cli.sh -d /data/sonic-vm -m $(inventory) -t $(testbed_file) -k ceos refresh-dut $(tbname) password.txt; ./testbed-cli.sh -m $(inventory) -t $(testbed_file) deploy-mg $(tbname) lab password.txt" && sleep 180
       displayName: "Setup T0 testbed"
 
-    - script: |
-        pwd
-        username=$(id -un)
-        rm -rf $(Build.ArtifactStagingDirectory)/*
 
-        IMAGE_LOCATION="https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-202012/lastSuccessfulBuild/artifact/target/sonic-vs.img.gz"
-        IMAGE_LIST="current"
-        CONTINUOUS_REBOOT_COUNT=1
-        CONTINUOUS_REBOOT_DELAY=300
 
-        # EXTRA_ARGS="\'--image_location=$IMAGE_LOCATION --image_list=$IMAGE_LIST --reboot_type=warm --continuous_reboot_count=1 --continuous_reboot_delay=300\'"
-        # CMD="cd /data/sonic-mgmt/tests/ ; /data/sonic-mgmt/tests/run_tests.sh \
-        # -n $(tbname) -d $(dut) -c /data/sonic-mgmt/tests/platform_tests/test_cont_warm_reboot.py \
-        # -f /data/sonic-mgmt/ansible/vtestbed.csv -i /data/sonic-mgmt/ansible/veos_vtb -l info \
-        # -e $EXTRA_ARGS"
+    - ${{ each firm in parameters.firms }}:
+      - script: |
+          pwd
+          username=$(id -un)
+          rm -rf $(Build.ArtifactStagingDirectory)/*
 
-        CMD="cd /data/sonic-mgmt/tests/ ; \
-        export ANSIBLE_CONFIG=/data/sonic-mgmt/ansible ANSIBLE_LIBRARY=/data/sonic-mgmt/ansible/library/; \
-        pytest platform_tests/test_cont_warm_reboot.py \
-              --continuous_reboot_count=$CONTINUOUS_REBOOT_COUNT \
-              --continuous_reboot_delay=$CONTINUOUS_REBOOT_DELAY \
-              --testbed=$(tbname) --host-pattern=$(tbname) --inventory=/data/sonic-mgmt/ansible/veos_vtb \
-              --testbed_file=/data/sonic-mgmt/ansible/vtestbed.csv --module-path=/data/sonic-mgmt/ansible/library \
-              --show-capture=no --log-cli-level=INFO  \
-              --image_location=$IMAGE_LOCATION --image_list=$IMAGE_LIST \
-              --reboot_type=warm --skip_sanity"
+          IMAGE_LOCATION="https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs-image-202012/lastSuccessfulBuild/artifact/target/sonic-vs.img.gz"
+          IMAGE_LIST="current"
+          CONTINUOUS_REBOOT_COUNT=1
+          CONTINUOUS_REBOOT_DELAY=300
 
-        LOG_CMD="mv /data/sonic-mgmt/tests/continous_reboot_* /data/sonic-mgmt/tests/logs/ || true"
+          # EXTRA_ARGS="\'--image_location=$IMAGE_LOCATION --image_list=$IMAGE_LIST --reboot_type=warm --continuous_reboot_count=1 --continuous_reboot_delay=300\'"
+          # CMD="cd /data/sonic-mgmt/tests/ ; /data/sonic-mgmt/tests/run_tests.sh \
+          # -n $(tbname) -d $(dut) -c /data/sonic-mgmt/tests/platform_tests/test_cont_warm_reboot.py \
+          # -f /data/sonic-mgmt/ansible/vtestbed.csv -i /data/sonic-mgmt/ansible/veos_vtb -l info \
+          # -e $EXTRA_ARGS"
 
-        echo "Continuous warm reboot test command: $CMD"
+          CMD="cd /data/sonic-mgmt/tests/ ; \
+          export ANSIBLE_CONFIG=/data/sonic-mgmt/ansible ANSIBLE_LIBRARY=/data/sonic-mgmt/ansible/library/; \
+          pytest platform_tests/test_cont_warm_reboot.py \
+                --continuous_reboot_count=$CONTINUOUS_REBOOT_COUNT \
+                --continuous_reboot_delay=$CONTINUOUS_REBOOT_DELAY \
+                --testbed=$(tbname) --host-pattern=$(tbname) --inventory=/data/sonic-mgmt/ansible/veos_vtb \
+                --testbed_file=/data/sonic-mgmt/ansible/vtestbed.csv --module-path=/data/sonic-mgmt/ansible/library \
+                --show-capture=no --log-cli-level=INFO  \
+                --image_location=$IMAGE_LOCATION --image_list=$IMAGE_LIST \
+                --reboot_type=warm --skip_sanity"
 
-        declare -i iteration
-        iteration=1
+          LOG_CMD="mv /data/sonic-mgmt/tests/continous_reboot_* /data/sonic-mgmt/tests/logs/ || true"
 
-        while true; do
-            sleep 5
-            SIGNAL_COLLECTOR="TEST_RUNNING"
-            echo "##vso[task.setvariable variable=SIGNAL_READY;isOutput=true;]$SIGNAL_COLLECTOR"
+          echo "Continuous warm reboot test command: $CMD"
 
-            echo "================ iteration ${iteration} ==================="
-            # docker exec sonic-mgmt bash -c "$CMD"
-            sleep 5
+          declare -i iteration
+          iteration=1
 
-            SIGNAL_COLLECTOR="RESULTS_READY"
-            echo "##vso[task.setvariable variable=SIGNAL_READY;isOutput=true;]$SIGNAL_COLLECTOR"
-            continue
+          while true; do
+              sleep 5
+              echo "================ iteration ${iteration} started==================="
+              #docker exec sonic-mgmt bash -c "$CMD"
 
-            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                # fail and stop all the remaining batches if pytest fails
-                echo "Batch iteration ${iteration}+ failed"
-                docker exec sonic-mgmt bash -c "$LOG_CMD"
-                exit 2
-            fi
-            docker exec sonic-mgmt bash -c "$LOG_CMD"
-            sleep 60
-            echo "----------------------------------------------------"
-            iteration=iteration+100
-        done
+              if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                  # fail and stop all the remaining batches if pytest fails
+                  echo "Batch iteration ${iteration}+ failed"
+                  #docker exec sonic-mgmt bash -c "$LOG_CMD"
+                  exit 2
+              fi
+              #docker exec sonic-mgmt bash -c "$LOG_CMD"
+              sleep 60
+              echo "================ iteration ${iteration} completed==================="
+              iteration=iteration+1
+          done
 
-        # save dut state if test fails
+          # save dut state if test fails
 
-        if [ $? != 0 ]; then
-            virsh_version=$(virsh --version)
-            if [ $virsh_version == "6.0.0" ]; then
-                mkdir -p $(Build.ArtifactStagingDirectory)/kvmdump
-                virsh -c qemu:///system list
-                virsh -c qemu:///system save $(dut) $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).memdmp
-                virsh -c qemu:///system dumpxml $(dut) > $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).xml
-                img=$(virsh -c qemu:///system domblklist $(dut) | grep vda | awk '{print $2}')
-                cp $img $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).img
-                virsh -c qemu:///system undefine $(dut)
-            fi
+          if [ $? != 0 ]; then
+              virsh_version=$(virsh --version)
+              if [ $virsh_version == "6.0.0" ]; then
+                  mkdir -p $(Build.ArtifactStagingDirectory)/kvmdump
+                  virsh -c qemu:///system list
+                  virsh -c qemu:///system save $(dut) $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).memdmp
+                  virsh -c qemu:///system dumpxml $(dut) > $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).xml
+                  img=$(virsh -c qemu:///system domblklist $(dut) | grep vda | awk '{print $2}')
+                  cp $img $(Build.ArtifactStagingDirectory)/kvmdump/$(dut).img
+                  virsh -c qemu:///system undefine $(dut)
+              fi
 
-            docker commit $(ptf_name) docker-ptf:$(Build.BuildNumber)
-            docker save docker-ptf:$(Build.BuildNumber) | gzip -c > $(Build.ArtifactStagingDirectory)/kvmdump/docker-ptf-dump.gz
-            docker rmi docker-ptf:$(Build.BuildNumber)
+              docker commit $(ptf_name) docker-ptf:$(Build.BuildNumber)
+              docker save docker-ptf:$(Build.BuildNumber) | gzip -c > $(Build.ArtifactStagingDirectory)/kvmdump/docker-ptf-dump.gz
+              docker rmi docker-ptf:$(Build.BuildNumber)
 
-            cp -r /data/sonic-mgmt/tests/logs $(Build.ArtifactStagingDirectory)/
-            sudo chown -R $username.$username $(Build.ArtifactStagingDirectory)
+              cp -r /data/sonic-mgmt/tests/logs $(Build.ArtifactStagingDirectory)/
+              sudo chown -R $username.$username $(Build.ArtifactStagingDirectory)
 
-            exit 2
-        else
-            cp -r /data/sonic-mgmt/tests/logs $(Build.ArtifactStagingDirectory)/
-        fi
-      displayName: "Run continuous warmboot tests"
-      continueOnError: true
+              exit 2
+          else
+              cp -r /data/sonic-mgmt/tests/logs $(Build.ArtifactStagingDirectory)/
+          fi
+        displayName: "Run continuous warmboot tests"
+        continueOnError: true
+
+      - publish: $(Build.ArtifactStagingDirectory)/logs/continous_reboot_*
+        artifact: sonic-buildimage.kvmtest.log@$(System.JobAttempt)
+        displayName: "Archive sonic kvm logs"
+        condition: succeededOrFailed()
+        continueOnError: true
+
+
+
+
 
     - publish: $(Build.ArtifactStagingDirectory)/kvmdump
       artifact: sonic-buildimage.kvmtest.memdump@$(System.JobAttempt)
       displayName: "Archive sonic kvm memdump"
       condition: failed()
 
-    - publish: $(Build.ArtifactStagingDirectory)/logs/continous_reboot_*
-      artifact: sonic-buildimage.kvmtest.log@$(System.JobAttempt)
-      displayName: "Archive sonic kvm logs"
-      condition: succeededOrFailed()
-      continueOnError: true
-
     - task: PublishTestResults@2
       inputs:
         testResultsFiles: '$(Build.ArtifactStagingDirectory)/logs/**/*.xml'
         testRunTitle: kvmtest
       condition: succeededOrFailed()
-
-  - job: job_deploy_code
-    displayName: Collect and report new results
-    dependsOn: ['kvmWarmbootTest']
-    variables: 
-      SIGNAL_READY: $[ dependencies.kvmWarmbootTest.outputs['SIGNAL_READY'] ]
-    steps: 
-    - script: |
-        "Results ready: $(SIGNAL_READY)"
-        while true; do
-            if [ $(SIGNAL_READY) == "TEST_RUNNING" ]; then
-              echo "TEST_RUNNING"
-            fi
-            if [ $(SIGNAL_READY) == "RESULTS_READY" ]; then
-              echo "RESULTS_READY"
-            fi
-        done
