Incase pre-commit runs it requires pylint and deps due to tests/common2 but they won't be run as files are filtered

diff --git a/.azure-pipelines/pre-commit-check.yml b/.azure-pipelines/pre-commit-check.yml
--- a/.azure-pipelines/pre-commit-check.yml
+++ b/.azure-pipelines/pre-commit-check.yml
@@ -15,9 +15,20 @@ steps:
 
 - script: |
     set -x
-    sudo pip install pre-commit
+    timeout 180s sudo apt-get update -y || {
+      echo "apt-get update failed or timed out"
+      exit 1
+    }
+    # Install aspell and aspell-en non-interactively
+    timeout 180s sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends aspell aspell-en libenchant-2-2 libenchant-2-dev || {
+      echo "Failed to install aspell or aspell-en or libenchant-2-2 or libenchant-2-dev"
+      exit 1
+    }
+    pip install pyenchant
+    pip install pylint # required as pylint is run in local mode
+    pip install -r tests/common2/requirements.txt
+
     pre-commit install-hooks
-    sudo pip install pylint
   displayName: 'Prepare pre-commit check'
 
 - script: |
