[Baseline] Fix 1 testplan fail may cancel others issue (#12978)
What is the motivation for this PR?
Baseline test will run a batch of PR tests, and in baseline test, test plan in same platform will run in 1 test job in azure devops.
In current logic, once a test plan fails, the test job would catch the sys.exit code and cancel following steps, but we want it only cancel following steps when all test plans fail in the test job

How did you do it?
Use set -o to continue bash command when fails, get the return code of polling test plan status, if all polling results fail, raise exit code to cancel following steps

diff --git a/.azure-pipelines/run-test-elastictest-template.yml b/.azure-pipelines/run-test-elastictest-template.yml
--- a/.azure-pipelines/run-test-elastictest-template.yml
+++ b/.azure-pipelines/run-test-elastictest-template.yml
@@ -277,10 +277,38 @@ steps:
             fi
         done
 
+<<<<<<< HEAD
         if [ $failure_count -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
             echo "All testplan failed, cancel following steps"
             exit 3
         fi
+=======
+  - script: |
+      set -o
+      echo "Lock testbed"
+
+      echo -e "\033[33mSONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com \033[0m"
+      IFS=',' read -ra TEST_PLAN_ID_LIST <<< "$TEST_PLAN_ID_LIST_STRING"
+      failure_count=0
+      for TEST_PLAN_ID in "${TEST_PLAN_ID_LIST[@]}"
+      do
+          echo -e -n "\033[33mPlease visit Elastictest page \033[0m"
+          echo -n "$(FRONTEND_URL)/scheduler/testplan/$TEST_PLAN_ID "
+          echo -e "\033[33mfor detailed test plan progress \033[0m"
+          # When "LOCK_TESTBED" finish, it changes into "PREPARE_TESTBED"
+          echo "[test_plan.py] poll LOCK_TESTBED status"
+          python ./.azure-pipelines/test_plan.py poll -i $TEST_PLAN_ID --expected-state LOCK_TESTBED
+          RET=$?
+          if [ $RET -ne 0 ]; then
+              ((failure_count++))
+          fi
+      done
+>>>>>>> [Baseline] Fix 1 testplan fail may cancel others issue (#12978)
+
+      if [ $failure_count -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
+          echo "All testplan failed, cancel following steps"
+          exit 3
+      fi
 
     displayName: "Lock testbed"
     env:
@@ -313,10 +341,39 @@ steps:
             fi
         done
 
+<<<<<<< HEAD
         if [ "$failure_count" -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
             echo "All testplan failed, cancel following steps"
             exit 3
         fi
+=======
+  - script: |
+      set -o
+      echo "Prepare testbed"
+      echo "Preparing the testbed(add-topo, deploy-mg) may take 15-30 minutes. Before the testbed is ready, the progress of the test plan keeps displayed as 0, please be patient"
+
+      echo -e "\033[33mSONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com \033[0m"
+      IFS=',' read -ra TEST_PLAN_ID_LIST <<< "$TEST_PLAN_ID_LIST_STRING"
+      failure_count=0
+      for TEST_PLAN_ID in "${TEST_PLAN_ID_LIST[@]}"
+      do
+          echo -e -n "\033[33mPlease visit Elastictest page \033[0m"
+          echo -n "$(FRONTEND_URL)/scheduler/testplan/$TEST_PLAN_ID "
+          echo -e "\033[33mfor detailed test plan progress \033[0m"
+          # When "PREPARE_TESTBED" finish, it changes into "EXECUTING"
+          echo "[test_plan.py] poll PREPARE_TESTBED status"
+          python ./.azure-pipelines/test_plan.py poll -i $TEST_PLAN_ID --expected-state PREPARE_TESTBED
+          RET=$?
+          if [ $RET -ne 0 ]; then
+              ((failure_count++))
+          fi
+      done
+>>>>>>> [Baseline] Fix 1 testplan fail may cancel others issue (#12978)
+
+      if [ "$failure_count" -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
+          echo "All testplan failed, cancel following steps"
+          exit 3
+      fi
 
     displayName: "Prepare testbed"
     env:
@@ -348,10 +405,38 @@ steps:
             fi
         done
 
+<<<<<<< HEAD
         if [ $failure_count -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
             echo "All testplan failed, cancel following steps"
             exit 3
         fi
+=======
+  - script: |
+      set -o
+      echo "Run test"
+
+      echo -e "\033[33mSONiC PR system-level test is powered by SONiC Elastictest, for any issue, please send email to sonicelastictest@microsoft.com \033[0m"
+      IFS=',' read -ra TEST_PLAN_ID_LIST <<< "$TEST_PLAN_ID_LIST_STRING"
+      failure_count=0
+      for TEST_PLAN_ID in "${TEST_PLAN_ID_LIST[@]}"
+      do
+          echo -e -n "\033[33mPlease visit Elastictest page \033[0m"
+          echo -n "$(FRONTEND_URL)/scheduler/testplan/$TEST_PLAN_ID "
+          echo -e "\033[33mfor detailed test plan progress \033[0m"
+          # When "EXECUTING" finish, it changes into "KVMDUMP", "FAILED", "CANCELLED" or "FINISHED"
+          echo "[test_plan.py] poll EXECUTING status"
+          python ./.azure-pipelines/test_plan.py poll -i $TEST_PLAN_ID --expected-state EXECUTING --expected-result ${{ parameters.EXPECTED_RESULT }}
+          RET=$?
+          if [ $RET -ne 0 ]; then
+              ((failure_count++))
+          fi
+      done
+>>>>>>> [Baseline] Fix 1 testplan fail may cancel others issue (#12978)
+
+      if [ $failure_count -eq ${#TEST_PLAN_ID_LIST[@]} ]; then
+          echo "All testplan failed, cancel following steps"
+          exit 3
+      fi
 
     displayName: "Run test"
     timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
