Merged PR 2536: Enhance testbedv2 scheduler template (#8207)
Enhance testbedv2 scheduler template (#8207)

* Enhance testbedv2 scheduler template, remove kvm_dump step is not needed, support to set max execute time

Approach
What is the motivation for this PR?
Enhance testbedv2 scheduler template:

Remove kvm_dump step if it is not needed.
Support to set max execute time.

co-authorized by: jianquanye@microsoft.com

diff --git a/.azure-pipelines/run-test-scheduler-template.yml b/.azure-pipelines/run-test-scheduler-template.yml
--- a/.azure-pipelines/run-test-scheduler-template.yml
+++ b/.azure-pipelines/run-test-scheduler-template.yml
@@ -92,15 +92,18 @@ parameters:
 
 - name: DUMP_KVM_IF_FAIL
   type: string
-  default: ""
+  default: "True"
+  values:
+  - "True"
+  - "False"
 
 - name: REQUESTER
   type: string
   default: ""
 
-- name: MAX_EXECUTE_SECONDS
-  type: string
-  default: ""
+- name: MAX_RUN_TEST_MINUTES
+  type: number
+  default: 480
 
 - name: SPECIFIED_PARAMS
   type: string
@@ -135,7 +138,7 @@ steps:
       --retry-times ${{ parameters.RETRY_TIMES }} \
       --dump-kvm-if-fail ${{ parameters.DUMP_KVM_IF_FAIL }} \
       --requester "${{ parameters.REQUESTER }}" \
-      --max-execute-seconds ${{ parameters.MAX_EXECUTE_SECONDS }}
+      --max-execute-seconds $((${{ parameters.MAX_RUN_TEST_MINUTES }} * 60))
 
       TEST_PLAN_ID=`cat new_test_plan_id.txt`
 
@@ -192,21 +195,23 @@ steps:
       CLIENT_ID: $(TESTBED_TOOLS_MSAL_CLIENT_ID)
       CLIENT_SECRET: $(TESTBED_TOOLS_MSAL_CLIENT_SECRET)
     displayName: Run test
+    timeoutInMinutes: ${{ parameters.MAX_RUN_TEST_MINUTES }}
 
-  - script: |
-      set -e
-      echo "KVM dump"
-      echo "TestbedV2 is just online and might not be stable enough, for any issue, please send email to sonictestbedtools@microsoft.com"
-      echo "Runtime detailed progress at https://www.testbed-tools.org/scheduler/testplan/$TEST_PLAN_ID "
-      # When "KVMDUMP" finish, it changes into "FAILED", "CANCELLED" or "FINISHED"
-      python ./.azure-pipelines/test_plan.py poll -i "$(TEST_PLAN_ID)" --expected-state KVMDUMP
-    condition: succeededOrFailed()
-    env:
-      TESTBED_TOOLS_URL: $(TESTBED_TOOLS_URL)
-      TENANT_ID: $(TESTBED_TOOLS_MSAL_TENANT_ID)
-      CLIENT_ID: $(TESTBED_TOOLS_MSAL_CLIENT_ID)
-      CLIENT_SECRET: $(TESTBED_TOOLS_MSAL_CLIENT_SECRET)
-    displayName: KVM dump
+  - ${{ if eq(parameters.DUMP_KVM_IF_FAIL, 'True') }}:
+    - script: |
+        set -e
+        echo "KVM dump"
+        echo "TestbedV2 is just online and might not be stable enough, for any issue, please send email to sonictestbedtools@microsoft.com"
+        echo "Runtime detailed progress at https://www.testbed-tools.org/scheduler/testplan/$TEST_PLAN_ID "
+        # When "KVMDUMP" finish, it changes into "FAILED", "CANCELLED" or "FINISHED"
+        python ./.azure-pipelines/test_plan.py poll -i "$(TEST_PLAN_ID)" --expected-state KVMDUMP
+      condition: succeededOrFailed()
+      env:
+        TESTBED_TOOLS_URL: $(TESTBED_TOOLS_URL)
+        TENANT_ID: $(TESTBED_TOOLS_MSAL_TENANT_ID)
+        CLIENT_ID: $(TESTBED_TOOLS_MSAL_CLIENT_ID)
+        CLIENT_SECRET: $(TESTBED_TOOLS_MSAL_CLIENT_SECRET)
+      displayName: KVM dump
 
   - script: |
       set -e
